// Generated by CoffeeScript 1.10.0
(function() {
  var examples, running;

  window.section = function(title) {
    return $('<h2>').text(title).appendTo($('#output'));
  };

  window.print = function(text) {
    var $content, $p;
    $content = $('#output');
    $p = null;
    if ($content.children().length === 0) {
      $p = $('<p>').appendTo($content);
    } else if ($content.find('*').last()[0].tagName === 'H2') {
      $p = $('<p>').appendTo($content);
    } else {
      $p = $content.find('p:last');
    }
    return $('<span>').text(text).appendTo($p);
  };

  window.println = function(text) {
    return $('<p>').text(text).appendTo($('#output'));
  };

  examples = [];

  running = false;

  window.example = function(title, fn) {
    var callback;
    callback = function() {
      var dfd;
      section(title);
      dfd = jQuery.Deferred();
      dfd.then(function() {
        var newCallback;
        if (examples.length > 0) {
          newCallback = examples.shift();
          return newCallback();
        } else {
          return running = false;
        }
      });
      return fn(dfd.resolve);
    };
    if (running) {
      return examples.push(callback);
    } else {
      running = true;
      return callback();
    }
  };

}).call(this);
