// Generated by CoffeeScript 1.10.0
(function() {
  example('timer', function(done) {
    return Rx.Observable.timer(1000, 1000).take(5).subscribe(function(x) {
      return print(x);
    }, null, done);
  });

  example('range', function(done) {
    return Rx.Observable.range(9, 5).subscribe(function(x) {
      return print(x);
    }, null, done);
  });

  example('fromArray', function(done) {
    return Rx.Observable.fromArray(['a', 'b', 'c']).subscribe(function(x) {
      return print(x);
    }, null, done);
  });

}).call(this);
